/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.sun.awt.AWTUtilities;
import controlador.funciones;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.getSet;

/**
 *
 * @author alex_
 */
public class vista extends javax.swing.JFrame {
int xE;
int yE;
getSet gs = new getSet();
funciones f = new funciones();
    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        this.setTitle("CAFÉ");
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        
        gs.setCafe(1000);
        f.mostrarCafe(gs.getCafe(), this.lblCantidad);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnLlenar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JLabel();
        btnServir = new javax.swing.JLabel();
        btnVaciar = new javax.swing.JLabel();
        brnAgregar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        iconlbl.setIcon(new javax.swing.ImageIcon("img/grains-cup-coffee (2).jpg"));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 94, 97));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CAFÉ");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(99, 94, 97));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCantidad.setText("CANTIDAD DE CAFÉ");
        lblCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLlenar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLlenar.setForeground(new java.awt.Color(99, 94, 97));
        btnLlenar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLlenar.setIcon(new javax.swing.ImageIcon("img/cafetera.png"));
        btnLlenar.setText("LLENAR CAFETERA");
        btnLlenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLlenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLlenarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLlenarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLlenarMouseEntered(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(99, 94, 97));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setText("SALIR");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        btnServir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnServir.setForeground(new java.awt.Color(99, 94, 97));
        btnServir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServir.setIcon(new javax.swing.ImageIcon("img/taza.png"));
        btnServir.setText("SERVIR TAZA");
        btnServir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServirMouseEntered(evt);
            }
        });

        btnVaciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVaciar.setForeground(new java.awt.Color(99, 94, 97));
        btnVaciar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVaciar.setIcon(new javax.swing.ImageIcon("img/vaciar.png"));
        btnVaciar.setText("VACIAR  CAFETERA");
        btnVaciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVaciarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVaciarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVaciarMouseEntered(evt);
            }
        });

        brnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        brnAgregar.setForeground(new java.awt.Color(99, 94, 97));
        brnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        brnAgregar.setIcon(new javax.swing.ImageIcon("img/agregar.png"));
        brnAgregar.setText("AGREGAR CAFÉ");
        brnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brnAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brnAgregarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brnAgregarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnServir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 234, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(brnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLlenar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnServir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(478, Short.MAX_VALUE)
                    .addComponent(brnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(iconlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
          xE = evt.getX();
        yE = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
      this.setLocation(this.getLocation().x + evt.getX() - xE, this.getLocation().y + evt.getY() - yE);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
      btnSalir.setForeground(new java.awt.Color(99, 94, 97));
    }//GEN-LAST:event_btnSalirMouseExited

    private void brnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnAgregarMouseEntered
        brnAgregar.setForeground(Color.red);
    }//GEN-LAST:event_brnAgregarMouseEntered

    private void btnVaciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseEntered
       btnVaciar.setForeground(Color.red);
    }//GEN-LAST:event_btnVaciarMouseEntered

    private void btnServirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServirMouseEntered
      btnServir.setForeground(Color.red);
    }//GEN-LAST:event_btnServirMouseEntered

    private void btnLlenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLlenarMouseEntered
       btnLlenar.setForeground(Color.red);
    }//GEN-LAST:event_btnLlenarMouseEntered

    private void brnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnAgregarMouseExited
        brnAgregar.setForeground(new java.awt.Color(99, 94, 97));
    }//GEN-LAST:event_brnAgregarMouseExited

    private void btnVaciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseExited
       btnVaciar.setForeground(new java.awt.Color(99, 94, 97));
    }//GEN-LAST:event_btnVaciarMouseExited

    private void btnServirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServirMouseExited
        btnServir.setForeground(new java.awt.Color(99, 94, 97));
    }//GEN-LAST:event_btnServirMouseExited

    private void btnLlenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLlenarMouseExited
        btnLlenar.setForeground(new java.awt.Color(99, 94, 97));
    }//GEN-LAST:event_btnLlenarMouseExited

    private void btnLlenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLlenarMouseClicked
       if(gs.getCafe() >= 1000){
      JOptionPane.showMessageDialog(rootPane, "LA CAFETERA YA SE ENCUENTRA EN SU MÁXIMA CAPACIDAD", "CUIDADO", JOptionPane.WARNING_MESSAGE);
       }else{
        gs.setCafe(1000);
        f.mostrarCafe(gs.getCafe(), lblCantidad);
       }  
    }//GEN-LAST:event_btnLlenarMouseClicked

    private void btnVaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseClicked
       gs.setCafe(0);
       f.mostrarCafe(gs.getCafe(), lblCantidad);
    }//GEN-LAST:event_btnVaciarMouseClicked

    private void brnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnAgregarMouseClicked
         if(gs.getCafe() >= 1000){
        JOptionPane.showMessageDialog(rootPane, "LA CAFETERA YA SE ENCUENTRA EN SU MÁXIMA CAPACIDAD", "CUIDADO", JOptionPane.WARNING_MESSAGE);
        } else {
        
            String cantidad = JOptionPane.showInputDialog("INGRESE LA CANTIDAD DE CAFÉ");
            
            if(f.validarNumero(cantidad)){
            int cant = Integer.parseInt(cantidad);
            
          int cafeApeend = gs.getCafe() + cant;
            
          if(cafeApeend > 1000){
              
               gs.setCafe(1000);
          f.mostrarCafe(gs.getCafe(), lblCantidad);
          JOptionPane.showMessageDialog(rootPane, "NO PUEDES SUPERAR LOS 1000ML", "ERROR", JOptionPane.WARNING_MESSAGE);
          }else {
         gs.setCafe(cafeApeend);
            
            f.mostrarCafe(gs.getCafe(), lblCantidad);
          }
            }else {
            JOptionPane.showMessageDialog(rootPane, "INGRESE UN NÚMERO", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_brnAgregarMouseClicked

    private void btnServirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServirMouseClicked
        if(gs.getCafe() <= 0){
        JOptionPane.showMessageDialog(rootPane, "POR FAVOR, LLENE LA CAFETERA ANTES DE SERVIR CAFÉ");
        }else {
        
        String cantidadServir = JOptionPane.showInputDialog("Ingrese la cantidad a servir en ML");
        if (f.validarNumero(cantidadServir)){
        
            int cs = Integer.parseInt(cantidadServir);
            int taza = gs.getCafe() - cs;
            if(cs > gs.getCafe()){
            JOptionPane.showMessageDialog(rootPane, "LA CANTIDAD DE CAFÉ QUE QUIERE SERVIR \n" + "ES MAYOR A LA "
                    + "CANTIDAD DE CAFÉ QUE TIENE EN LA CAFETERA,\n SE SIRVIERON: " + gs.getCafe() + "ML DE CAFÉ");
            gs.setCafe(0);
            f.mostrarCafe(gs.getCafe(), lblCantidad);
            } else{
            gs.setCafe(taza);
            f.mostrarCafe(gs.getCafe(), lblCantidad);
            }
            
            }else{
        JOptionPane.showMessageDialog(rootPane, "DEBE INGRESAR LA CANTIDAD EN NÚMEROS!", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnServirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brnAgregar;
    private javax.swing.JLabel btnLlenar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnServir;
    private javax.swing.JLabel btnVaciar;
    private javax.swing.JLabel iconlbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantidad;
    // End of variables declaration//GEN-END:variables
}
